#undef __FILE_ID__
#define __FILE_ID__ 0x0A
/**
 * PyMite std native function file
 *
 * automatically created by pmImgCreator.py
 * on Wed May 24 16:08:10 2017
 *
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 *
 * @file    inc/py_std_native.c
 */

#define __IN_LIBNATIVE_C__
#include "py_pm.h"
#include "string.h"
#include "deviceDefs.h"

/* From: Modules\len_sys.py */
#include "stdint.h"

char str_buf[255]; //Global buffer

//Get uint8_t value by index
uint8_t py_get_uint8_t(uint8_t id) {
	pPmObj_t val_in;
	val_in = NATIVE_GET_LOCAL(id);
	return ((pPmInt_t)val_in)->val;
}

//Get float value by index
float py_get_float(uint8_t id) {
	pPmObj_t val_in;
	val_in = NATIVE_GET_LOCAL(id);
	return ((pPmFloat_t)val_in)->val;
}

//Get string value by index
void py_get_string(uint8_t id, char *str, uint16_t *len) {
	pPmObj_t val_in;
	
	val_in = NATIVE_GET_LOCAL(id);
	memset(str,0,sizeof(str));
	memcpy(str, ((pPmString_t)val_in)->val, ((pPmString_t)val_in)->length);
	*len = ((pPmString_t)val_in)->length;
}

//Get function name
PmReturn_t py_get_functionName(char *name) {
	pPmObj_t pframe;
	pPmObj_t pstr;
	PmReturn_t retval = PM_RET_OK;
	
	/* Get the top frame */
	pframe = (pPmObj_t)gVmGlobal.pthread->pframe;
	
	retval = tuple_getItem((pPmObj_t)((pPmFrame_t)pframe)->fo_func->f_co->co_names, -1, &pstr);	
	sprintf(name,"%s",((pPmString_t)pstr)->val);

	return retval;
}

//Add int to list
PmReturn_t py_add_int_toList(int val, pPmObj_t *list) {
	pPmObj_t pi;
	PmReturn_t retval = PM_RET_OK;

	retval = int_new(val, &pi);
	if (retval == PM_RET_OK)
		retval = list_append(*list, pi);

	return retval;
}

//Add string to list
PmReturn_t py_add_str_toList(char* str, pPmObj_t *list) {
	pPmObj_t ps;
	PmReturn_t retval = PM_RET_OK;

	retval = string_new(str, &ps);

	if (retval == PM_RET_OK)
		retval = list_append(*list, ps);

	return retval;
}


//Check error code
uint8_t py_error_check(DEV_Status_t cmd_exec, uint8_t type_dev, uint8_t adr_sw, uint8_t adr_port) {
	if (cmd_exec != DEV_OK) {
		pPmObj_t pframe;
		pPmObj_t pstr;
		
		py_error.type_dev = type_dev;
		py_error.adr_sw = adr_sw;
		py_error.adr_port = adr_port;
		py_error.error_code = cmd_exec;

		/* Get the top frame */
		pframe = (pPmObj_t)gVmGlobal.pthread->pframe;
		tuple_getItem((pPmObj_t)((pPmFrame_t)pframe)->fo_func->f_co->co_names, -1, &pstr);	
		memcpy((void *)py_error.thread_name,((pPmString_t)pstr)->val,sizeof(py_error.thread_name));
		
		return 1;
	}else{
		return 0;
	}
}

/* From: Modules\sizeof.py */
#include "py_pm.h"

/* From: Modules\string.py */
#include <stdlib.h>
#include <string.h>

PmReturn_t
nat_00_len_adc_getChVal_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	float val;
	pPmObj_t val_obj;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	
	//Get value
	cmd_exec = PI_getChVal(type_dev,adr_sw,adr_port, &val);
	
	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	//Convert object
	retval = float_new(val,&val_obj);
	NATIVE_SET_TOS(val_obj);
	return retval;
	
}

PmReturn_t
nat_01_len_adc_setChMode_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	uint8_t mode = py_get_uint8_t(3);
	
	//Set mode
	cmd_exec = PI_setChMode(type_dev,adr_sw,adr_port, mode);

	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_02_len_adc_setChOffset_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	float offset = py_get_float(3);
	
	//Set offset
	cmd_exec = PI_setChOffset(type_dev,adr_sw,adr_port, offset);

	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_03_len_adc_getChOffset_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	float val;
	pPmObj_t val_obj;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	
	//Get offset
	cmd_exec = PI_getChOffset(type_dev,adr_sw,adr_port, &val);

	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	//Convert object
	retval = float_new(val,&val_obj);
	NATIVE_SET_TOS(val_obj);
	return retval;
	
}

PmReturn_t
nat_04_len_adc_setChKoef_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	float koef = py_get_float(3);
	
	//Set koef
	cmd_exec = PI_setChKoef(type_dev,adr_sw,adr_port, koef);

	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_05_len_adc_getChKoef_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	float val;
	pPmObj_t val_obj;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	
	//Get koefficient
	cmd_exec = PI_getChKoef(type_dev,adr_sw,adr_port, &val);

	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	//Convert object
	retval = float_new(val,&val_obj);
	NATIVE_SET_TOS(val_obj);
	return retval;
	
}

PmReturn_t
nat_06_len_digIO_setModeOut_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	uint8_t mode = py_get_uint8_t(3);
	
	//Set mode
	cmd_exec = PI_digitalOut_mode_set(type_dev,adr_sw,adr_port, mode);

	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_07_len_digIO_setPwmOut_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	uint8_t value = py_get_uint8_t(3);
	
	//Read value
	cmd_exec = PI_digitalOut_PWM_set(type_dev,adr_sw,adr_port, value);
	
	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_08_len_digIO_getPwmOut_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	pPmObj_t val_obj;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	uint8_t value;
	
	//Read value
	cmd_exec = PI_digitalOut_PWM_get(type_dev,adr_sw,adr_port, &value);
	
	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	//Convert object
	retval = int_new(value, &val_obj);
	NATIVE_SET_TOS(val_obj);
	return retval;
	
}

PmReturn_t
nat_09_len_digIO_setDigOut_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	uint8_t value = py_get_uint8_t(3);
	
	//Set value
	cmd_exec = PI_digitalOut_set(type_dev,adr_sw,adr_port, value);
	
	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_10_len_digIO_getDigOut_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	pPmObj_t val_obj;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	uint8_t value;
	
	//Read value
	cmd_exec = PI_digitalOut_get(type_dev,adr_sw,adr_port, &value);
	
	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	//Convert object
	retval = int_new(value, &val_obj);
	NATIVE_SET_TOS(val_obj);
	return retval;
	
}

PmReturn_t
nat_11_len_digIO_setInvOut_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	uint8_t value = py_get_uint8_t(3);
	
	//Inver value
	cmd_exec = PI_digitalOut_invert(type_dev,adr_sw,adr_port);
	
	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_12_len_digIO_setModeIn_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	uint8_t mode = py_get_uint8_t(3);

	//Set input mode
	cmd_exec = PI_digitalIn_mode_set(type_dev,adr_sw,adr_port,mode);

	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_13_len_digIO_resCounterIn_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);

	//Reset counter value
	cmd_exec = PI_digitalIn_reset_counter(type_dev,adr_sw,adr_port);

	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_14_len_digIO_getDigIn_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	pPmObj_t val_obj;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);
	uint8_t value;

	//Read value
	cmd_exec = PI_digitalIn_get(type_dev,adr_sw,adr_port, &value);
	
	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	//Convert object
	retval = int_new(value, &val_obj);
	NATIVE_SET_TOS(val_obj);
	return retval;
	
}

PmReturn_t
nat_15_len_digIO_getCounterIn_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	pPmObj_t val_obj;
	uint32_t counter = 0;
	
	//Getting values
	uint8_t type_dev = py_get_uint8_t(0);
	uint8_t adr_sw = py_get_uint8_t(1);
	uint8_t adr_port = py_get_uint8_t(2);

	//Get counter value
	cmd_exec = PI_digitalIn_get_counter(type_dev,adr_sw,adr_port, &counter);

	py_error_check(cmd_exec, type_dev, adr_sw, adr_port);
	
	if (py_error_check(cmd_exec, type_dev, adr_sw, adr_port))
		retval = PM_RET_ERR;
	
	retval = int_new(counter, &val_obj);
	NATIVE_SET_TOS(val_obj);

	return retval;
	
}

PmReturn_t
nat_16_len_mqtt_setIPport_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	char ip_str[15];
	char port_str[5];
	uint16_t ip_len, port_len;
	
	//Getting values
     py_get_string(0, ip_str, &ip_len); //Get string value by index
     py_get_string(1, port_str, &port_len); //Get string value by index
     
	//Set ip
	cmd_exec = PI_mqtt_SetIPport(ip_str, port_str);
	
	if (py_error_check(cmd_exec, 0, 0, 0))
		retval = PM_RET_ERR;
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_17_len_mqtt_getIPport(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t pl;
	char ip_str[15];
	char port_str[5];
     
	//Get ip
	PI_mqtt_GetIPport(ip_str, port_str);
	
	retval = list_new(&pl);
	py_add_str_toList(ip_str, &pl);
	py_add_str_toList(port_str, &pl);
	
    	NATIVE_SET_TOS(pl);

	return retval;
	
}

PmReturn_t
nat_18_len_mqtt_setLoginPass_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	char login[50];
	char pass[50];
	uint16_t login_len, pass_len;
	
	//Getting values
     py_get_string(0, login, &login_len); //Get string value by index
     py_get_string(1, pass, &pass_len); //Get string value by index
     
	//Set ip
	cmd_exec = PI_mqtt_SetLoginPass(login, pass);
	
	if (py_error_check(cmd_exec, 0, 0, 0))
		retval = PM_RET_ERR;
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_19_len_mqtt_getLoginPass(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t pl;
	char login[50];
	char pass[50];
     
	//Get ip
	PI_mqtt_GetLoginPass(login, pass);

	retval = list_new(&pl);
	py_add_str_toList(login, &pl);
	py_add_str_toList(pass, &pl);
	
    	NATIVE_SET_TOS(pl);
	return retval;
	
}

PmReturn_t
nat_20_len_mqtt_setChannel_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	
	uint8_t channel = py_get_uint8_t(0);

	//SetChannel
	cmd_exec = PI_mqtt_setChannel(channel);
	
	if (py_error_check(cmd_exec, 0, 0, 0))
		retval = PM_RET_ERR;
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_21_len_mqtt_getChannel(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t channel_obj;
	uint8_t channel;

	PI_mqtt_getChannel(&channel);
	
	retval = int_new(channel, &channel_obj);
	NATIVE_SET_TOS(channel_obj);
	return retval;
	
}

PmReturn_t
nat_22_len_mqtt_pubMessage_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	char topic[20];
	uint16_t topic_len, message_len;

	memset(topic,0,sizeof(topic));

	//Getting values
     py_get_string(0, topic, &topic_len); //Get string value by index
     py_get_string(1, str_buf, &message_len); //Get string value by index

     cmd_exec = PI_mqtt_pubMessage(topic, str_buf);

     if (py_error_check(cmd_exec, 0, 0, 0))
		retval = PM_RET_ERR;

	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_23_len_mqtt_subTopic_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	DEV_Status_t cmd_exec;
	char topic[20];
	uint16_t topic_len;

	memset(topic,0,sizeof(topic));
	
	//Getting values
     py_get_string(0, topic, &topic_len); //Get string value by index

     cmd_exec = PI_mqtt_subTopic(topic);

     if (py_error_check(cmd_exec, 0, 0, 0))
		retval = PM_RET_ERR;

	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_24_len_mqtt_getStatus(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t pi;

	retval = int_new(MQTT_state.MQTT_status, &pi);	

	NATIVE_SET_TOS(pi);
	return retval;
	
}

PmReturn_t
nat_25_len_sys_delay_ms(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t ms_val;
	ms_val = NATIVE_GET_LOCAL(0);
	vTaskDelay(((pPmInt_t)ms_val)->val);
	NATIVE_SET_TOS(PM_NONE);
	return retval;
     
}

PmReturn_t
nat_26_len_sys_kill_Thread(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_EX;
	return retval;
	
}

PmReturn_t
nat_27_len_sys_func_name(pPmFrame_t *ppframe)
{

	char buf[30];
	pPmObj_t ps;
	pPmObj_t pframe;
	pPmObj_t pstr;
	
	PmReturn_t retval = PM_RET_OK;
	
	/* Get the top frame */
	pframe = (pPmObj_t)gVmGlobal.pthread->pframe;
	
	retval = tuple_getItem((pPmObj_t)((pPmFrame_t)pframe)->fo_func->f_co->co_names, -1, &pstr);	
	sprintf(buf,"%s",((pPmString_t)pstr)->val);	
	if (retval == PM_RET_OK) {
		retval = string_new(buf, &ps);
    		NATIVE_SET_TOS(ps);
    	}
    	
	return retval;
	
}

PmReturn_t
nat_28_len_sys_get_error(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t pl;
	
	retval = list_new(&pl);
	py_add_int_toList(py_error.type_dev, &pl);
	py_add_int_toList(py_error.adr_sw, &pl);
	py_add_int_toList(py_error.adr_port, &pl);
	py_add_int_toList(py_error.error_code, &pl);
	py_add_str_toList(py_error.thread_name, &pl);

	NATIVE_SET_TOS(pl);
	return retval;
	
}

PmReturn_t
nat_29_len_sys_addCallback(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t pf;
	pPmObj_t ps;
	char buf[20];

	/* If wrong number of args, raise TypeError */
	if (NATIVE_GET_NUM_ARGS() != 1)
	{
	   PM_RAISE(retval, PM_RET_EX_TYPE);
	   return retval;
	}

	//Check type
	pf = NATIVE_GET_LOCAL(0);
	if (OBJ_GET_TYPE(pf) != OBJ_TYPE_FXN)
	{
	   PM_RAISE(retval, PM_RET_EX_TYPE);
	   return retval;
	}

	//Get function name
	retval = tuple_getItem((pPmObj_t)((pPmFunc_t)pf)->f_co->co_names, -1, &ps);	
	sprintf(buf,"%s",((pPmString_t)ps)->val);	

	//Search function by name
	for (int i=0; i<PY_COUNT_CALLBACKS; i++) {
		if (strstr(py_callback[i].callback_name, buf) !=0){
			py_callback[i].py_func = pf; //Record function
			py_callback[i].callback_status = PY_CALLBACK_STOP; //Record status
			NATIVE_SET_TOS(PM_NONE);
			retval = PM_RET_OK;
			return retval;
		}
	}
	
	NATIVE_SET_TOS(PM_NONE);
	retval = PM_RET_NO;
	return retval;
	
}

PmReturn_t
nat_30_len_sys_ClearCallback(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	char name[20];
	
	//Get function name
     py_get_functionName(name); 	

	//Search function by name
	for (int i=0; i<PY_COUNT_CALLBACKS; i++) {
		if (strstr(py_callback[i].callback_name, name) !=0){
			py_callback[i].callback_status = PY_CALLBACK_STOP; //Record status
			NATIVE_SET_TOS(PM_NONE);
			retval = PM_RET_OK;
			return retval;
		}
	}
	
	NATIVE_SET_TOS(PM_NONE);
	retval = PM_RET_NO;
	return retval;
	
}

PmReturn_t
nat_31_len_sys_getCallbackValue(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	char name[20];
	pPmObj_t pl;
	
	//Get function name
     py_get_functionName(name); 	

     //Search function by name
	for (int i=0; i<PY_COUNT_CALLBACKS; i++) {
		if (strstr(py_callback[i].callback_name, name) !=0){
			retval = list_new(&pl);

			//Make params
			switch(i) {
			case PY_SMS_CALLBACK:
				break;
			case PY_MQTT_CALLBACK:
				py_add_str_toList(((py_var_MQTT_CALLBACK_type *)((py_var_GPIO_CALLBACK_type*)py_callback->callback_val))->ip_addr, &pl);
				py_add_str_toList(((py_var_MQTT_CALLBACK_type *)((py_var_GPIO_CALLBACK_type*)py_callback->callback_val))->port, &pl);
				py_add_str_toList(((py_var_MQTT_CALLBACK_type *)((py_var_GPIO_CALLBACK_type*)py_callback->callback_val))->topic, &pl);
				py_add_str_toList(((py_var_MQTT_CALLBACK_type *)((py_var_GPIO_CALLBACK_type*)py_callback->callback_val))->message, &pl);
				py_add_int_toList(((py_var_MQTT_CALLBACK_type *)((py_var_GPIO_CALLBACK_type*)py_callback->callback_val))->len, &pl);
				break;
			case PY_GPIO_CALLBACK:
				py_add_int_toList(((py_var_GPIO_CALLBACK_type *)((py_var_GPIO_CALLBACK_type*)py_callback->callback_val))->type_dev, &pl);
				py_add_int_toList(((py_var_GPIO_CALLBACK_type *)((py_var_GPIO_CALLBACK_type*)py_callback->callback_val))->adr_sw, &pl);
				py_add_int_toList(((py_var_GPIO_CALLBACK_type *)((py_var_GPIO_CALLBACK_type*)py_callback->callback_val))->adr_port, &pl);
				py_add_int_toList(((py_var_GPIO_CALLBACK_type *)((py_var_GPIO_CALLBACK_type*)py_callback->callback_val))->value, &pl);			
				break;
			case PY_DISPLAY_CALLBACK:
				break;
			case PY_MODEM_CALLBACK:
				break;
			case PY_PY_BLUETOOTH_CALLBACK:
				break;
			case PY_RF_CALLBACK:
				break;
			}
			
			NATIVE_SET_TOS(pl);
			retval = PM_RET_OK;
			return retval;
		}
	}
	
	NATIVE_SET_TOS(PM_NONE);
	retval = PM_RET_NO;
	return retval;
	
}

PmReturn_t
nat_32_list_append(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    PmReturn_t retval = PM_RET_OK;

    /* Raise TypeError if it's not a list or wrong number of args, */
    pl = NATIVE_GET_LOCAL(0);
    if ((OBJ_GET_TYPE(pl) != OBJ_TYPE_LST) || (NATIVE_GET_NUM_ARGS() != 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Append the object to the list */
    retval = list_append(pl, NATIVE_GET_LOCAL(1));

    NATIVE_SET_TOS(PM_NONE);

    return retval;
    
}

PmReturn_t
nat_33_list_index(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    pPmObj_t po;
    pPmObj_t pi;
    PmReturn_t retval = PM_RET_OK;
    uint16_t i;

    /* Raise TypeError if it's not a list or wrong number of args, */
    pl = NATIVE_GET_LOCAL(0);
    if ((OBJ_GET_TYPE(pl) != OBJ_TYPE_LST) || (NATIVE_GET_NUM_ARGS() != 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Get the index of the object in the list */
    po = NATIVE_GET_LOCAL(1);
    retval = list_index(pl, po, &i);

    if (retval == PM_RET_EX_VAL)
    {
        PM_RAISE(retval, PM_RET_EX_VAL);
        return retval;
    }

    int_new((int32_t)i, &pi);
    NATIVE_SET_TOS(pi);

    return retval;
    
}

PmReturn_t
nat_34_list_insert(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    pPmObj_t pi;
    pPmObj_t po;
    PmReturn_t retval = PM_RET_OK;
    uint16_t i;

    /*
     * Raise TypeError if wrong number of args, first arg is not a list, or
     * second arg is not an int
     */
    pl = NATIVE_GET_LOCAL(0);
    pi = NATIVE_GET_LOCAL(1);
    po = NATIVE_GET_LOCAL(2);
    if ((NATIVE_GET_NUM_ARGS() != 3)
        || (OBJ_GET_TYPE(pl) != OBJ_TYPE_LST)
        || (OBJ_GET_TYPE(pi) != OBJ_TYPE_INT) )
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Insert the object before the given index */
    i = (uint16_t)((pPmInt_t)pi)->val;
    retval = list_insert(pl, i, po);

    if (retval != PM_RET_OK)
    {
        PM_RAISE(retval, PM_RET_EX_SYS);
    }

    NATIVE_SET_TOS(PM_NONE);

    return retval;
    
}

PmReturn_t
nat_35_list_pop(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    pPmObj_t pi;
    pPmObj_t po;
    PmReturn_t retval = PM_RET_OK;
    int16_t i;

    /*
     * Raise TypeError if first arg is not a list o second arg is not an int
     * or there are the wrong number of arguments
     */
    pl = NATIVE_GET_LOCAL(0);
    if (OBJ_GET_TYPE(pl) != OBJ_TYPE_LST)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    pi = NATIVE_GET_LOCAL(1);
    if (NATIVE_GET_NUM_ARGS() == 2)
    {
        if (OBJ_GET_TYPE(pi) != OBJ_TYPE_INT)
        {
            PM_RAISE(retval, PM_RET_EX_TYPE);
            return retval;
        }
        i = (uint16_t)((pPmInt_t)pi)->val;
    }
    else
    {
        i = -1;
    }
    if ((NATIVE_GET_NUM_ARGS() < 1) || (NATIVE_GET_NUM_ARGS() > 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Get the object at the given index */
    retval = list_getItem(pl, i, &po);
    PM_RETURN_IF_ERROR(retval);

    /* Return the object to the caller */
    NATIVE_SET_TOS(po);

    /* Remove the object from the given index */
    retval = list_delItem(pl, i);
    PM_RETURN_IF_ERROR(retval);

    return retval;
    
}

PmReturn_t
nat_36_list_remove(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    pPmObj_t pv;
    PmReturn_t retval = PM_RET_OK;

    /* Raise TypeError if it's not a list or wrong number of args, */
    pl = NATIVE_GET_LOCAL(0);
    if ((OBJ_GET_TYPE(pl) != OBJ_TYPE_LST) || (NATIVE_GET_NUM_ARGS() != 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Remove the value from the list */
    pv = NATIVE_GET_LOCAL(1);
    retval = list_remove(pl, pv);
    if (retval != PM_RET_OK)
    {
        PM_RAISE(retval, retval);
    }

    NATIVE_SET_TOS(PM_NONE);

    return retval;
    
}

PmReturn_t
nat_37_sizeof_sizeof(pPmFrame_t *ppframe)
{

    pPmObj_t pobj;
    pPmObj_t psize;
    int32_t n;
    PmReturn_t retval = PM_RET_OK;
    int32_t static size[] = {
        sizeof(PmObj_t), /* None type */
        sizeof(PmInt_t),
        sizeof(PmFloat_t),
        sizeof(PmString_t),
        sizeof(PmTuple_t),
        sizeof(PmCo_t),
        sizeof(PmFunc_t), /* Module Obj uses func struct */
        sizeof(PmClass_t),
        sizeof(PmFunc_t),
        sizeof(PmClass_t), /* Class instance */
        0, /* CIM */
        0, /* NIM */
        sizeof(PmCo_t), /* NOB */
        sizeof(PmThread_t),
        sizeof(PmClass_t), /* Exception instance */
        sizeof(PmBoolean_t),
        sizeof(PmCodeImgObj_t),
        sizeof(PmList_t),
        sizeof(PmDict_t),
        0,
        0,
        0,
        0,
        0,
        0,
        sizeof(PmFrame_t),
        sizeof(PmBlock_t),
        sizeof(Segment_t),
        sizeof(Seglist_t),
        sizeof(PmSeqIter_t),
        sizeof(PmNativeFrame_t),
    };

    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 1)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    pobj = NATIVE_GET_LOCAL(0);
    if (OBJ_GET_TYPE(pobj) == OBJ_TYPE_INT)
    {
        n = ((pPmInt_t)pobj)->val;
        if ((n >= 0) && (n < 32))
        {
            /* Return the size of the type represented by the integer */
            retval = int_new(size[n], &psize);
        }
        else
        {
            /* Return the size of an integer object */
            retval = int_new(OBJ_GET_SIZE(pobj), &psize);
        }
    }
    else
    {
        /* Return the size of the given non-integer object */
        retval = int_new(OBJ_GET_SIZE(pobj), &psize);
    }

    NATIVE_SET_TOS(psize);
    return retval;
    
}

PmReturn_t
nat_38_string_atoi(pPmFrame_t *ppframe)
{

    pPmObj_t pa;
    pPmObj_t pb;
    char const *pc;
    char *pend;
    long i;
    int8_t base;
    pPmObj_t pi;
    PmReturn_t retval = PM_RET_OK;

    /* Raise TypeError if it's not a string or wrong number of args, */
    pa = NATIVE_GET_LOCAL(0);
    if ((OBJ_GET_TYPE(pa) != OBJ_TYPE_STR) || (NATIVE_GET_NUM_ARGS() < 1)
        || (NATIVE_GET_NUM_ARGS() > 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Get the base, if it exists; otherwise assume 10 */
    base = 10;
    if (NATIVE_GET_NUM_ARGS() == 2)
    {
        pb = NATIVE_GET_LOCAL(1);

        /* Raise a TypeError if 2nd arg is not an int */
        if (OBJ_GET_TYPE(pb) != OBJ_TYPE_INT)
        {
            PM_RAISE(retval, PM_RET_EX_TYPE);
            return retval;
        }

        base = ((pPmInt_t)pb)->val;

        /* Raise ValueError if base is out of range */
        if ((base < 0) || (base == 1) || (base > 36))
        {
            PM_RAISE(retval, PM_RET_EX_VAL);
            return retval;
        }
    }

    /* Perform conversion */
    pend = C_NULL;
    pc = (char const *)&(((pPmString_t)pa)->val);
    i = strtol(pc, &pend, base);

    /* Raise ValueError if there was a conversion error */
    if (*pend != C_NULL)
    {
        PM_RAISE(retval, PM_RET_EX_VAL);
        return retval;
    }

    /* Create an int object to hold the result of the conversion */
    retval = int_new(i, &pi);

    NATIVE_SET_TOS(pi);

    return retval;
    
}

PmReturn_t
nat_39_string_count(pPmFrame_t *ppframe)
{

    pPmObj_t ps1;
    pPmObj_t ps2;
    uint8_t *pc1;
    uint8_t *pc2;
    uint8_t *pscan;
    uint8_t *pmatch;
    uint8_t pc2c0;
    uint16_t pc1len;
    uint16_t pc2len;
    uint16_t n;
    uint16_t remaining;
    uint16_t cmp;
    pPmObj_t pn;
    PmReturn_t retval = PM_RET_OK;

    /* Raise TypeError if it's not a string or wrong number of args, */
    ps1 = NATIVE_GET_LOCAL(0);
    ps2 = NATIVE_GET_LOCAL(1);
    if ((OBJ_GET_TYPE(ps1) != OBJ_TYPE_STR) || (NATIVE_GET_NUM_ARGS() != 2)
        || (OBJ_GET_TYPE(ps2) != OBJ_TYPE_STR))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    pc1 = ((pPmString_t)ps1)->val;
    pc2 = ((pPmString_t)ps2)->val;
    pc1len = ((pPmString_t)ps1)->length;
    pc2len = ((pPmString_t)ps2)->length;
    n = 0;

    /* Handle some quick special cases (order of if-clauses is important) */
    if (pc2len == 0)
    {
        n = pc1len + 1;
    }
    else if (pc1len == 0)
    {
        n = 0;
    }

    /* Count the number of matches */
    else
    {
        n = 0;
        remaining = pc1len;
        pscan = pc1;
        pc2c0 = pc2[0];
        while (pscan <= (pc1 + (pc1len - pc2len)))
        {
            /* Find the next possible start */
            pmatch = (uint8_t *)memchr(pscan, pc2c0, remaining);
            if (pmatch == C_NULL) break;
            remaining -= (pmatch - pscan);
            pscan = pmatch;

            /* If it matches, increase the count, else try the next char */
            cmp = memcmp(pscan, pc2, pc2len);
            if (cmp == 0)
            {
                n++;
                pscan += pc2len;
                remaining -= pc2len;
            }
            else
            {
                pscan++;
                remaining--;
            }
        }
    }

    retval = int_new(n, &pn);

    NATIVE_SET_TOS(pn);

    return retval;
    
}

PmReturn_t
nat_40_string_find(pPmFrame_t *ppframe)
{

    pPmObj_t ps1;
    pPmObj_t ps2;
    uint8_t *pc1;
    uint8_t *pc2;
    uint8_t *pmatch;
    uint8_t pc1len;
    uint8_t pc2len;
    int32_t n;
    pPmObj_t pn;
    PmReturn_t retval = PM_RET_OK;

    /* Raise TypeError if it's not a string or wrong number of args, */
    ps1 = NATIVE_GET_LOCAL(0);
    ps2 = NATIVE_GET_LOCAL(1);
    if ((OBJ_GET_TYPE(ps1) != OBJ_TYPE_STR) || (NATIVE_GET_NUM_ARGS() != 2)
        || (OBJ_GET_TYPE(ps2) != OBJ_TYPE_STR))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    pc1 = ((pPmString_t)ps1)->val;
    pc2 = ((pPmString_t)ps2)->val;
    pc1len = ((pPmString_t)ps1)->length;
    pc2len = ((pPmString_t)ps2)->length;
    n = -1;

    /* Handle a quick special case */
    if (pc2len == 0)
    {
        n = 0;
    }

    /* Try to find the index of the substring */
    else
    {
        /* Find the next possible start */
        pmatch = (uint8_t *)memchr(pc1, pc2[0], pc1len);
        if (pmatch != C_NULL)
        {
            /* If it matches, calculate the index */
            if (memcmp(pmatch, pc2, pc2len) == 0)
            {
                n = pmatch - pc1;
            }
        }
    }

    retval = int_new(n, &pn);

    NATIVE_SET_TOS(pn);

    return retval;
    
}

PmReturn_t
nat_41_sys_exit(pPmFrame_t *ppframe)
{

    pPmObj_t pval = C_NULL;
    PmReturn_t retval;

    /* If no arg given, assume return 0 */
    if (NATIVE_GET_NUM_ARGS() == 0)
    {
        NATIVE_SET_TOS(PM_ZERO);
    }

    /* If 1 arg given, put it on stack */
    else if (NATIVE_GET_NUM_ARGS() == 1)
    {
        pval = NATIVE_GET_LOCAL(0);
        NATIVE_SET_TOS(pval);
    }

    /* If wrong number of args, raise TypeError */
    else
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Raise the SystemExit exception */
    PM_RAISE(retval, PM_RET_EX_EXIT);
    return retval;
    
}

PmReturn_t
nat_42_sys_gc(pPmFrame_t *ppframe)
{

    PmReturn_t retval = PM_RET_OK;
#ifdef HAVE_GC
    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 0)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    retval = heap_gcRun();
#endif
    NATIVE_SET_TOS(PM_NONE);

    return retval;
    
}

PmReturn_t
nat_43_sys_getb(pPmFrame_t *ppframe)
{

    uint8_t b;
    pPmObj_t pb;
    PmReturn_t retval;

    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 0)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    retval = plat_getByte(&b);
    PM_RETURN_IF_ERROR(retval);

    retval = int_new((int32_t)b, &pb);
    NATIVE_SET_TOS(pb);
    return retval;
    
}

PmReturn_t
nat_44_sys_heap(pPmFrame_t *ppframe)
{

    PmReturn_t retval;
    pPmObj_t pavail;
    pPmObj_t pmax;
    pPmObj_t ptup;
    uint8_t objid;

    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 0)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Allocate a tuple to store the return values */
    retval = tuple_new(2, &ptup);
    PM_RETURN_IF_ERROR(retval);

    /* Get the maximum heap size */
    heap_gcPushTempRoot(ptup, &objid);
    retval = int_new(PM_HEAP_SIZE, &pmax);
    if (retval != PM_RET_OK)
    {
        heap_gcPopTempRoot(objid);
        return retval;
    }

    /* Allocate an int to hold the amount of heap available */
    retval = int_new(heap_getAvail() - sizeof(PmInt_t), &pavail);
    heap_gcPopTempRoot(objid);
    PM_RETURN_IF_ERROR(retval);

    /* Put the two heap values in the tuple */
    ((pPmTuple_t)ptup)->val[0] = pavail;
    ((pPmTuple_t)ptup)->val[1] = pmax;

    /* Return the tuple on the stack */
    NATIVE_SET_TOS(ptup);

    return retval;
    
}

PmReturn_t
nat_45_sys_putb(pPmFrame_t *ppframe)
{

    uint8_t b;
    pPmObj_t pb;
    PmReturn_t retval;

    pb = NATIVE_GET_LOCAL(0);

    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 1)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* If arg is not an int, raise TypeError */
    if (OBJ_GET_TYPE(pb) != OBJ_TYPE_INT)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    b = ((pPmInt_t)pb)->val & 0xFF;
    retval = plat_putByte(b);
    NATIVE_SET_TOS(PM_NONE);
    return retval;
    
}

PmReturn_t
nat_46_sys_runInThread(pPmFrame_t *ppframe)
{

    PmReturn_t retval;
    pPmObj_t pf;

    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 1)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* If arg is not a function, raise TypeError */
    pf = NATIVE_GET_LOCAL(0);
    if (OBJ_GET_TYPE(pf) != OBJ_TYPE_FXN)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    retval = interp_addThread((pPmFunc_t)pf);
    NATIVE_SET_TOS(PM_NONE);
    return retval;
    
}

PmReturn_t
nat_47_sys_time(pPmFrame_t *ppframe)
{

    uint32_t t;
    pPmObj_t pt;
    PmReturn_t retval;

    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 0)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Get the system time (milliseconds since init) */
    retval = plat_getMsTicks(&t);
    PM_RETURN_IF_ERROR(retval);

    /*
     * Raise ValueError if there is an overflow
     * (plat_getMsTicks is unsigned; int is signed)
     */
    if ((int32_t)t < 0)
    {
        PM_RAISE(retval, PM_RET_EX_VAL);
        return retval;
    }

    /* Return an int object with the time value */
    retval = int_new((int32_t)t, &pt);
    NATIVE_SET_TOS(pt);
    return retval;
    
}

/* Native function lookup table */
pPmNativeFxn_t const std_nat_fxn_table[] =
{
    nat_00_len_adc_getChVal_nat,
    nat_01_len_adc_setChMode_nat,
    nat_02_len_adc_setChOffset_nat,
    nat_03_len_adc_getChOffset_nat,
    nat_04_len_adc_setChKoef_nat,
    nat_05_len_adc_getChKoef_nat,
    nat_06_len_digIO_setModeOut_nat,
    nat_07_len_digIO_setPwmOut_nat,
    nat_08_len_digIO_getPwmOut_nat,
    nat_09_len_digIO_setDigOut_nat,
    nat_10_len_digIO_getDigOut_nat,
    nat_11_len_digIO_setInvOut_nat,
    nat_12_len_digIO_setModeIn_nat,
    nat_13_len_digIO_resCounterIn_nat,
    nat_14_len_digIO_getDigIn_nat,
    nat_15_len_digIO_getCounterIn_nat,
    nat_16_len_mqtt_setIPport_nat,
    nat_17_len_mqtt_getIPport,
    nat_18_len_mqtt_setLoginPass_nat,
    nat_19_len_mqtt_getLoginPass,
    nat_20_len_mqtt_setChannel_nat,
    nat_21_len_mqtt_getChannel,
    nat_22_len_mqtt_pubMessage_nat,
    nat_23_len_mqtt_subTopic_nat,
    nat_24_len_mqtt_getStatus,
    nat_25_len_sys_delay_ms,
    nat_26_len_sys_kill_Thread,
    nat_27_len_sys_func_name,
    nat_28_len_sys_get_error,
    nat_29_len_sys_addCallback,
    nat_30_len_sys_ClearCallback,
    nat_31_len_sys_getCallbackValue,
    nat_32_list_append,
    nat_33_list_index,
    nat_34_list_insert,
    nat_35_list_pop,
    nat_36_list_remove,
    nat_37_sizeof_sizeof,
    nat_38_string_atoi,
    nat_39_string_count,
    nat_40_string_find,
    nat_41_sys_exit,
    nat_42_sys_gc,
    nat_43_sys_getb,
    nat_44_sys_heap,
    nat_45_sys_putb,
    nat_46_sys_runInThread,
    nat_47_sys_time,
};
