#undef __FILE_ID__
#define __FILE_ID__ 0x0A
/**
 * PyMite std native function file
 *
 * automatically created by pmImgCreator.py
 * on Wed Aug 29 20:31:58 2018
 *
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 *
 * @file    inc/py_std_native.c
 */

#define __IN_LIBNATIVE_C__
#include "py_pm.h"

/* From: Modules\dev_sys.py */
#include "stdint.h"
#include "string.h"
#include "TASK_script.h"
#include "DevCTRL.h"
#include "stm32f4xx_hal.h"

char str_buf[256]; //Global buffer

//Get uint8_t value by index
uint8_t py_get_uint8_t(uint8_t id) {
	pPmObj_t val_in;
	val_in = NATIVE_GET_LOCAL(id);
	return ((pPmInt_t)val_in)->val;
}

//Get float value by index
float py_get_float(uint8_t id) {
	pPmObj_t val_in;
	val_in = NATIVE_GET_LOCAL(id);
	return ((pPmFloat_t)val_in)->val;
}

//Get string value by index
void py_get_string(uint8_t id, char *str, uint16_t *len) {
	pPmObj_t val_in;
	
	val_in = NATIVE_GET_LOCAL(id);
	memset(str,0,sizeof(str));
	memcpy(str, ((pPmString_t)val_in)->val, ((pPmString_t)val_in)->length);
	*len = ((pPmString_t)val_in)->length;
}

//Get function name
PmReturn_t py_get_functionName(char *name) {
	pPmObj_t pframe;
	pPmObj_t pstr;
	PmReturn_t retval = PM_RET_OK;
	
	/* Get the top frame */
	pframe = (pPmObj_t)gVmGlobal.pthread->pframe;
	
	retval = tuple_getItem((pPmObj_t)((pPmFrame_t)pframe)->fo_func->f_co->co_names, -1, &pstr);	
	sprintf(name,"%s",((pPmString_t)pstr)->val);

	return retval;
}

//Add int to list
PmReturn_t py_add_int_toList(int val, pPmObj_t *list) {
	pPmObj_t pi;
	PmReturn_t retval = PM_RET_OK;

	retval = int_new(val, &pi);
	if (retval == PM_RET_OK)
		retval = list_append(*list, pi);

	return retval;
}

//Add string to list
PmReturn_t py_add_str_toList(char* str, pPmObj_t *list) {
	pPmObj_t ps;
	PmReturn_t retval = PM_RET_OK;

	retval = string_new(str, &ps);

	if (retval == PM_RET_OK)
		retval = list_append(*list, ps);

	return retval;
}

//Write error
void py_error_write(uint8_t error_code, uint8_t source) {

	pPmObj_t pframe;
	pPmObj_t pstr;
		
	PM_error.source = source;
	PM_error.error_code = error_code;

	/* Get the top frame */
	pframe = (pPmObj_t)gVmGlobal.pthread->pframe;
	tuple_getItem((pPmObj_t)((pPmFrame_t)pframe)->fo_func->f_co->co_names, -1, &pstr);	
	memcpy(PM_error.thread_name,((pPmString_t)pstr)->val,sizeof(PM_error.thread_name));
}

/* From: Modules\sizeof.py */
#include "py_pm.h"

/* From: Modules\string.py */
#include <stdlib.h>
#include <string.h>

PmReturn_t
nat_00_dev_sys_delay_ms(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t ms_val;
	ms_val = NATIVE_GET_LOCAL(0);
	vTaskDelay(((pPmInt_t)ms_val)->val);
	NATIVE_SET_TOS(PM_NONE);
	return retval;
     
}

PmReturn_t
nat_01_dev_sys_kill_Thread(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_EX;
	return retval;
	
}

PmReturn_t
nat_02_dev_sys_func_name(pPmFrame_t *ppframe)
{

	char buf[30];
	pPmObj_t ps;
	pPmObj_t pframe;
	pPmObj_t pstr;
	
	PmReturn_t retval = PM_RET_OK;
	
	/* Get the top frame */
	pframe = (pPmObj_t)gVmGlobal.pthread->pframe;
	
	retval = tuple_getItem((pPmObj_t)((pPmFrame_t)pframe)->fo_func->f_co->co_names, -1, &pstr);	
	sprintf(buf,"%s",((pPmString_t)pstr)->val);	
	if (retval == PM_RET_OK) {
		retval = string_new(buf, &ps);
    		NATIVE_SET_TOS(ps);
    	}
    	
	return retval;
	
}

PmReturn_t
nat_03_dev_sys_get_error(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t pl;
	uint8_t const *str = (uint8_t const *)PM_error.thread_name;

	uint8_t const *pstr = str;
	
	retval = list_new(&pl);
	py_add_int_toList(PM_error.source, &pl);
	py_add_int_toList(PM_error.error_code, &pl);
	py_add_str_toList((char*)pstr, &pl);

	NATIVE_SET_TOS(pl);
	return retval;
	
}

PmReturn_t
nat_04_dev_sys_addCallback(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t pf;
	pPmObj_t ps;
	char buf[20];

	/* If wrong number of args, raise TypeError */
	if (NATIVE_GET_NUM_ARGS() != 1)
	{
	   PM_RAISE(retval, PM_RET_EX_TYPE);
	   return retval;
	}

	//Check type
	pf = NATIVE_GET_LOCAL(0);
	if (OBJ_GET_TYPE(pf) != OBJ_TYPE_FXN)
	{
	   PM_RAISE(retval, PM_RET_EX_TYPE);
	   return retval;
	}

	//Get function name
	retval = tuple_getItem((pPmObj_t)((pPmFunc_t)pf)->f_co->co_names, -1, &ps);	
	sprintf(buf,"%s",((pPmString_t)ps)->val);	

	//Search function by name
	for (int i=0; i<PY_COUNT_CALLBACKS; i++) {
		if (strstr(PY_callback[i].callback_name, buf) !=0){
			PY_callback[i].PY_func = pf; //Record function
			PY_callback[i].callback_status = PY_CALLBACK_STOP; //Record status
			NATIVE_SET_TOS(PM_NONE);
			retval = PM_RET_OK;
			return retval;
		}
	}
	
	NATIVE_SET_TOS(PM_NONE);
	retval = PM_RET_NO;
	return retval;
	
}

PmReturn_t
nat_05_dev_sys_ClearCallback(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	char name[20];
	
	//Get function name
     py_get_functionName(name); 	

	//Search function by name
	for (int i=0; i<PY_COUNT_CALLBACKS; i++) {
		if (strstr(PY_callback[i].callback_name, name) !=0){
			PY_callback[i].callback_status = PY_CALLBACK_STOP; //Record status
			NATIVE_SET_TOS(PM_NONE);
			retval = PM_RET_OK;
			return retval;
		}
	}
	
	NATIVE_SET_TOS(PM_NONE);
	retval = PM_RET_NO;
	return retval;
	
}

PmReturn_t
nat_06_dev_sys_getCallbackValue(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	char name[20];
	pPmObj_t pl;
	
	//Get function name
     py_get_functionName(name); 	

     //Search function by name
	for (int i=0; i<PY_COUNT_CALLBACKS; i++) {
		if (strstr(PY_callback[i].callback_name, name) !=0){
			retval = list_new(&pl);

			//Make params
			switch(i) {
			case PY_MQTT_CALLBACK:
				break;
			case PY_GPIO_CALLBACK:	
				break;
			case PY_MODEM_CALLBACK:
				break;
			}
			
			NATIVE_SET_TOS(pl);
			retval = PM_RET_OK;
			return retval;
		}
	}
	
	NATIVE_SET_TOS(PM_NONE);
	retval = PM_RET_NO;
	return retval;
	
}

PmReturn_t
nat_07_digio_relayOut_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	HAL_StatusTypeDef retstat;
	
	//Getting values
	uint8_t relNum = py_get_uint8_t(0);
	uint8_t state = py_get_uint8_t(1);

	//Relay out
	retstat = DC_relayOut(relNum, state);
	
	if (retstat != HAL_OK)
	{
		py_error_write((uint8_t)retstat, relNum);
		retval = PM_RET_ERR;
	}
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_08_digio_ledOut(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	HAL_StatusTypeDef retstat;
	
	//Getting values
	uint8_t led = py_get_uint8_t(0);
	uint8_t state = py_get_uint8_t(1);

	//Relay out
	DC_LedOut((LED_t)led, state);
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_09_list_append(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    PmReturn_t retval = PM_RET_OK;

    /* Raise TypeError if it's not a list or wrong number of args, */
    pl = NATIVE_GET_LOCAL(0);
    if ((OBJ_GET_TYPE(pl) != OBJ_TYPE_LST) || (NATIVE_GET_NUM_ARGS() != 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Append the object to the list */
    retval = list_append(pl, NATIVE_GET_LOCAL(1));

    NATIVE_SET_TOS(PM_NONE);

    return retval;
    
}

PmReturn_t
nat_10_list_index(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    pPmObj_t po;
    pPmObj_t pi;
    PmReturn_t retval = PM_RET_OK;
    uint16_t i;

    /* Raise TypeError if it's not a list or wrong number of args, */
    pl = NATIVE_GET_LOCAL(0);
    if ((OBJ_GET_TYPE(pl) != OBJ_TYPE_LST) || (NATIVE_GET_NUM_ARGS() != 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Get the index of the object in the list */
    po = NATIVE_GET_LOCAL(1);
    retval = list_index(pl, po, &i);

    if (retval == PM_RET_EX_VAL)
    {
        PM_RAISE(retval, PM_RET_EX_VAL);
        return retval;
    }

    int_new((int32_t)i, &pi);
    NATIVE_SET_TOS(pi);

    return retval;
    
}

PmReturn_t
nat_11_list_insert(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    pPmObj_t pi;
    pPmObj_t po;
    PmReturn_t retval = PM_RET_OK;
    uint16_t i;

    /*
     * Raise TypeError if wrong number of args, first arg is not a list, or
     * second arg is not an int
     */
    pl = NATIVE_GET_LOCAL(0);
    pi = NATIVE_GET_LOCAL(1);
    po = NATIVE_GET_LOCAL(2);
    if ((NATIVE_GET_NUM_ARGS() != 3)
        || (OBJ_GET_TYPE(pl) != OBJ_TYPE_LST)
        || (OBJ_GET_TYPE(pi) != OBJ_TYPE_INT) )
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Insert the object before the given index */
    i = (uint16_t)((pPmInt_t)pi)->val;
    retval = list_insert(pl, i, po);

    if (retval != PM_RET_OK)
    {
        PM_RAISE(retval, PM_RET_EX_SYS);
    }

    NATIVE_SET_TOS(PM_NONE);

    return retval;
    
}

PmReturn_t
nat_12_list_pop(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    pPmObj_t pi;
    pPmObj_t po;
    PmReturn_t retval = PM_RET_OK;
    int16_t i;

    /*
     * Raise TypeError if first arg is not a list o second arg is not an int
     * or there are the wrong number of arguments
     */
    pl = NATIVE_GET_LOCAL(0);
    if (OBJ_GET_TYPE(pl) != OBJ_TYPE_LST)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    pi = NATIVE_GET_LOCAL(1);
    if (NATIVE_GET_NUM_ARGS() == 2)
    {
        if (OBJ_GET_TYPE(pi) != OBJ_TYPE_INT)
        {
            PM_RAISE(retval, PM_RET_EX_TYPE);
            return retval;
        }
        i = (uint16_t)((pPmInt_t)pi)->val;
    }
    else
    {
        i = -1;
    }
    if ((NATIVE_GET_NUM_ARGS() < 1) || (NATIVE_GET_NUM_ARGS() > 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Get the object at the given index */
    retval = list_getItem(pl, i, &po);
    PM_RETURN_IF_ERROR(retval);

    /* Return the object to the caller */
    NATIVE_SET_TOS(po);

    /* Remove the object from the given index */
    retval = list_delItem(pl, i);
    PM_RETURN_IF_ERROR(retval);

    return retval;
    
}

PmReturn_t
nat_13_list_remove(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    pPmObj_t pv;
    PmReturn_t retval = PM_RET_OK;

    /* Raise TypeError if it's not a list or wrong number of args, */
    pl = NATIVE_GET_LOCAL(0);
    if ((OBJ_GET_TYPE(pl) != OBJ_TYPE_LST) || (NATIVE_GET_NUM_ARGS() != 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Remove the value from the list */
    pv = NATIVE_GET_LOCAL(1);
    retval = list_remove(pl, pv);
    if (retval != PM_RET_OK)
    {
        PM_RAISE(retval, retval);
    }

    NATIVE_SET_TOS(PM_NONE);

    return retval;
    
}

PmReturn_t
nat_14_sizeof_sizeof(pPmFrame_t *ppframe)
{

    pPmObj_t pobj;
    pPmObj_t psize;
    int32_t n;
    PmReturn_t retval = PM_RET_OK;
    int32_t static size[] = {
        sizeof(PmObj_t), /* None type */
        sizeof(PmInt_t),
        sizeof(PmFloat_t),
        sizeof(PmString_t),
        sizeof(PmTuple_t),
        sizeof(PmCo_t),
        sizeof(PmFunc_t), /* Module Obj uses func struct */
        sizeof(PmClass_t),
        sizeof(PmFunc_t),
        sizeof(PmClass_t), /* Class instance */
        0, /* CIM */
        0, /* NIM */
        sizeof(PmCo_t), /* NOB */
        sizeof(PmThread_t),
        sizeof(PmClass_t), /* Exception instance */
        sizeof(PmBoolean_t),
        sizeof(PmCodeImgObj_t),
        sizeof(PmList_t),
        sizeof(PmDict_t),
        0,
        0,
        0,
        0,
        0,
        0,
        sizeof(PmFrame_t),
        sizeof(PmBlock_t),
        sizeof(Segment_t),
        sizeof(Seglist_t),
        sizeof(PmSeqIter_t),
        sizeof(PmNativeFrame_t),
    };

    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 1)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    pobj = NATIVE_GET_LOCAL(0);
    if (OBJ_GET_TYPE(pobj) == OBJ_TYPE_INT)
    {
        n = ((pPmInt_t)pobj)->val;
        if ((n >= 0) && (n < 32))
        {
            /* Return the size of the type represented by the integer */
            retval = int_new(size[n], &psize);
        }
        else
        {
            /* Return the size of an integer object */
            retval = int_new(PM_OBJ_GET_SIZE(pobj), &psize);
        }
    }
    else
    {
        /* Return the size of the given non-integer object */
        retval = int_new(PM_OBJ_GET_SIZE(pobj), &psize);
    }

    NATIVE_SET_TOS(psize);
    return retval;
    
}

PmReturn_t
nat_15_string_atoi(pPmFrame_t *ppframe)
{

    pPmObj_t pa;
    pPmObj_t pb;
    char const *pc;
    char *pend;
    long i;
    int8_t base;
    pPmObj_t pi;
    PmReturn_t retval = PM_RET_OK;

    /* Raise TypeError if it's not a string or wrong number of args, */
    pa = NATIVE_GET_LOCAL(0);
    if ((OBJ_GET_TYPE(pa) != OBJ_TYPE_STR) || (NATIVE_GET_NUM_ARGS() < 1)
        || (NATIVE_GET_NUM_ARGS() > 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Get the base, if it exists; otherwise assume 10 */
    base = 10;
    if (NATIVE_GET_NUM_ARGS() == 2)
    {
        pb = NATIVE_GET_LOCAL(1);

        /* Raise a TypeError if 2nd arg is not an int */
        if (OBJ_GET_TYPE(pb) != OBJ_TYPE_INT)
        {
            PM_RAISE(retval, PM_RET_EX_TYPE);
            return retval;
        }

        base = ((pPmInt_t)pb)->val;

        /* Raise ValueError if base is out of range */
        if ((base < 0) || (base == 1) || (base > 36))
        {
            PM_RAISE(retval, PM_RET_EX_VAL);
            return retval;
        }
    }

    /* Perform conversion */
    pend = C_NULL;
    pc = (char const *)&(((pPmString_t)pa)->val);
    i = strtol(pc, &pend, base);

    /* Raise ValueError if there was a conversion error */
    if (*pend != C_NULL)
    {
        PM_RAISE(retval, PM_RET_EX_VAL);
        return retval;
    }

    /* Create an int object to hold the result of the conversion */
    retval = int_new(i, &pi);

    NATIVE_SET_TOS(pi);

    return retval;
    
}

PmReturn_t
nat_16_string_count(pPmFrame_t *ppframe)
{

    pPmObj_t ps1;
    pPmObj_t ps2;
    uint8_t *pc1;
    uint8_t *pc2;
    uint8_t *pscan;
    uint8_t *pmatch;
    uint8_t pc2c0;
    uint16_t pc1len;
    uint16_t pc2len;
    uint16_t n;
    uint16_t remaining;
    uint16_t cmp;
    pPmObj_t pn;
    PmReturn_t retval = PM_RET_OK;

    /* Raise TypeError if it's not a string or wrong number of args, */
    ps1 = NATIVE_GET_LOCAL(0);
    ps2 = NATIVE_GET_LOCAL(1);
    if ((OBJ_GET_TYPE(ps1) != OBJ_TYPE_STR) || (NATIVE_GET_NUM_ARGS() != 2)
        || (OBJ_GET_TYPE(ps2) != OBJ_TYPE_STR))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    pc1 = ((pPmString_t)ps1)->val;
    pc2 = ((pPmString_t)ps2)->val;
    pc1len = ((pPmString_t)ps1)->length;
    pc2len = ((pPmString_t)ps2)->length;
    n = 0;

    /* Handle some quick special cases (order of if-clauses is important) */
    if (pc2len == 0)
    {
        n = pc1len + 1;
    }
    else if (pc1len == 0)
    {
        n = 0;
    }

    /* Count the number of matches */
    else
    {
        n = 0;
        remaining = pc1len;
        pscan = pc1;
        pc2c0 = pc2[0];
        while (pscan <= (pc1 + (pc1len - pc2len)))
        {
            /* Find the next possible start */
            pmatch = (uint8_t *)memchr(pscan, pc2c0, remaining);
            if (pmatch == C_NULL) break;
            remaining -= (pmatch - pscan);
            pscan = pmatch;

            /* If it matches, increase the count, else try the next char */
            cmp = memcmp(pscan, pc2, pc2len);
            if (cmp == 0)
            {
                n++;
                pscan += pc2len;
                remaining -= pc2len;
            }
            else
            {
                pscan++;
                remaining--;
            }
        }
    }

    retval = int_new(n, &pn);

    NATIVE_SET_TOS(pn);

    return retval;
    
}

PmReturn_t
nat_17_string_find(pPmFrame_t *ppframe)
{

    pPmObj_t ps1;
    pPmObj_t ps2;
    uint8_t *pc1;
    uint8_t *pc2;
    uint8_t *pmatch;
    uint8_t pc1len;
    uint8_t pc2len;
    int32_t n;
    pPmObj_t pn;
    PmReturn_t retval = PM_RET_OK;

    /* Raise TypeError if it's not a string or wrong number of args, */
    ps1 = NATIVE_GET_LOCAL(0);
    ps2 = NATIVE_GET_LOCAL(1);
    if ((OBJ_GET_TYPE(ps1) != OBJ_TYPE_STR) || (NATIVE_GET_NUM_ARGS() != 2)
        || (OBJ_GET_TYPE(ps2) != OBJ_TYPE_STR))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    pc1 = ((pPmString_t)ps1)->val;
    pc2 = ((pPmString_t)ps2)->val;
    pc1len = ((pPmString_t)ps1)->length;
    pc2len = ((pPmString_t)ps2)->length;
    n = -1;

    /* Handle a quick special case */
    if (pc2len == 0)
    {
        n = 0;
    }

    /* Try to find the index of the substring */
    else
    {
        /* Find the next possible start */
        pmatch = (uint8_t *)memchr(pc1, pc2[0], pc1len);
        if (pmatch != C_NULL)
        {
            /* If it matches, calculate the index */
            if (memcmp(pmatch, pc2, pc2len) == 0)
            {
                n = pmatch - pc1;
            }
        }
    }

    retval = int_new(n, &pn);

    NATIVE_SET_TOS(pn);

    return retval;
    
}

PmReturn_t
nat_18_sys_exit(pPmFrame_t *ppframe)
{

    pPmObj_t pval = C_NULL;
    PmReturn_t retval;

    /* If no arg given, assume return 0 */
    if (NATIVE_GET_NUM_ARGS() == 0)
    {
        NATIVE_SET_TOS(PM_ZERO);
    }

    /* If 1 arg given, put it on stack */
    else if (NATIVE_GET_NUM_ARGS() == 1)
    {
        pval = NATIVE_GET_LOCAL(0);
        NATIVE_SET_TOS(pval);
    }

    /* If wrong number of args, raise TypeError */
    else
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Raise the SystemExit exception */
    PM_RAISE(retval, PM_RET_EX_EXIT);
    return retval;
    
}

PmReturn_t
nat_19_sys_gc(pPmFrame_t *ppframe)
{

    PmReturn_t retval = PM_RET_OK;
#ifdef HAVE_GC
    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 0)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    retval = heap_gcRun();
#endif
    NATIVE_SET_TOS(PM_NONE);

    return retval;
    
}

PmReturn_t
nat_20_sys_getb(pPmFrame_t *ppframe)
{

    uint8_t b;
    pPmObj_t pb;
    PmReturn_t retval;

    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 0)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    retval = plat_getByte(&b);
    PM_RETURN_IF_ERROR(retval);

    retval = int_new((int32_t)b, &pb);
    NATIVE_SET_TOS(pb);
    return retval;
    
}

PmReturn_t
nat_21_sys_heap(pPmFrame_t *ppframe)
{

    PmReturn_t retval;
    pPmObj_t pavail;
    pPmObj_t pmax;
    pPmObj_t ptup;
    uint8_t objid;

    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 0)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Allocate a tuple to store the return values */
    retval = tuple_new(2, &ptup);
    PM_RETURN_IF_ERROR(retval);

    /* Get the maximum heap size */
    heap_gcPushTempRoot(ptup, &objid);
    retval = int_new(PM_HEAP_SIZE, &pmax);
    if (retval != PM_RET_OK)
    {
        heap_gcPopTempRoot(objid);
        return retval;
    }

    /* Allocate an int to hold the amount of heap available */
    retval = int_new(heap_getAvail() - sizeof(PmInt_t), &pavail);
    heap_gcPopTempRoot(objid);
    PM_RETURN_IF_ERROR(retval);

    /* Put the two heap values in the tuple */
    ((pPmTuple_t)ptup)->val[0] = pavail;
    ((pPmTuple_t)ptup)->val[1] = pmax;

    /* Return the tuple on the stack */
    NATIVE_SET_TOS(ptup);

    return retval;
    
}

PmReturn_t
nat_22_sys_putb(pPmFrame_t *ppframe)
{

    uint8_t b;
    pPmObj_t pb;
    PmReturn_t retval;

    pb = NATIVE_GET_LOCAL(0);

    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 1)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* If arg is not an int, raise TypeError */
    if (OBJ_GET_TYPE(pb) != OBJ_TYPE_INT)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    b = ((pPmInt_t)pb)->val & 0xFF;
    retval = plat_putByte(b);
    NATIVE_SET_TOS(PM_NONE);
    return retval;
    
}

PmReturn_t
nat_23_sys_runInThread(pPmFrame_t *ppframe)
{

    PmReturn_t retval;
    pPmObj_t pf;

    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 1)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* If arg is not a function, raise TypeError */
    pf = NATIVE_GET_LOCAL(0);
    if (OBJ_GET_TYPE(pf) != OBJ_TYPE_FXN)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    retval = interp_addThread((pPmFunc_t)pf);
    NATIVE_SET_TOS(PM_NONE);
    return retval;
    
}

PmReturn_t
nat_24_sys_time(pPmFrame_t *ppframe)
{

    uint32_t t;
    pPmObj_t pt;
    PmReturn_t retval;

    /* If wrong number of args, raise TypeError */
    if (NATIVE_GET_NUM_ARGS() != 0)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Get the system time (milliseconds since init) */
    retval = plat_getMsTicks(&t);
    PM_RETURN_IF_ERROR(retval);

    /*
     * Raise ValueError if there is an overflow
     * (plat_getMsTicks is unsigned; int is signed)
     */
    if ((int32_t)t < 0)
    {
        PM_RAISE(retval, PM_RET_EX_VAL);
        return retval;
    }

    /* Return an int object with the time value */
    retval = int_new((int32_t)t, &pt);
    NATIVE_SET_TOS(pt);
    return retval;
    
}

/* Native function lookup table */
pPmNativeFxn_t const std_nat_fxn_table[] =
{
    nat_00_dev_sys_delay_ms,
    nat_01_dev_sys_kill_Thread,
    nat_02_dev_sys_func_name,
    nat_03_dev_sys_get_error,
    nat_04_dev_sys_addCallback,
    nat_05_dev_sys_ClearCallback,
    nat_06_dev_sys_getCallbackValue,
    nat_07_digio_relayOut_nat,
    nat_08_digio_ledOut,
    nat_09_list_append,
    nat_10_list_index,
    nat_11_list_insert,
    nat_12_list_pop,
    nat_13_list_remove,
    nat_14_sizeof_sizeof,
    nat_15_string_atoi,
    nat_16_string_count,
    nat_17_string_find,
    nat_18_sys_exit,
    nat_19_sys_gc,
    nat_20_sys_getb,
    nat_21_sys_heap,
    nat_22_sys_putb,
    nat_23_sys_runInThread,
    nat_24_sys_time,
};
