#undef __FILE_ID__
#define __FILE_ID__ 0x0A
/**
 * PyMite std native function file
 *
 * automatically created by pmImgCreator.py
 * on Sun Aug 19 21:21:41 2018
 *
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 *
 * @file    inc/py_std_native.c
 */

#define __IN_LIBNATIVE_C__
#include "py_pm.h"

/* From: Modules\dev_sys.py */
#include "stdint.h"
#include "string.h"
#include "TASK_script.h"
#include "DevCTRL.h"

char str_buf[256]; //Global buffer

//Get uint8_t value by index
uint8_t py_get_uint8_t(uint8_t id) {
	pPmObj_t val_in;
	val_in = NATIVE_GET_LOCAL(id);
	return ((pPmInt_t)val_in)->val;
}

//Get float value by index
float py_get_float(uint8_t id) {
	pPmObj_t val_in;
	val_in = NATIVE_GET_LOCAL(id);
	return ((pPmFloat_t)val_in)->val;
}

//Get string value by index
void py_get_string(uint8_t id, char *str, uint16_t *len) {
	pPmObj_t val_in;
	
	val_in = NATIVE_GET_LOCAL(id);
	memset(str,0,sizeof(str));
	memcpy(str, ((pPmString_t)val_in)->val, ((pPmString_t)val_in)->length);
	*len = ((pPmString_t)val_in)->length;
}

//Get function name
PmReturn_t py_get_functionName(char *name) {
	pPmObj_t pframe;
	pPmObj_t pstr;
	PmReturn_t retval = PM_RET_OK;
	
	/* Get the top frame */
	pframe = (pPmObj_t)gVmGlobal.pthread->pframe;
	
	retval = tuple_getItem((pPmObj_t)((pPmFrame_t)pframe)->fo_func->f_co->co_names, -1, &pstr);	
	sprintf(name,"%s",((pPmString_t)pstr)->val);

	return retval;
}

//Add int to list
PmReturn_t py_add_int_toList(int val, pPmObj_t *list) {
	pPmObj_t pi;
	PmReturn_t retval = PM_RET_OK;

	retval = int_new(val, &pi);
	if (retval == PM_RET_OK)
		retval = list_append(*list, pi);

	return retval;
}

//Add string to list
PmReturn_t py_add_str_toList(char* str, pPmObj_t *list) {
	pPmObj_t ps;
	PmReturn_t retval = PM_RET_OK;

	retval = string_new(str, &ps);

	if (retval == PM_RET_OK)
		retval = list_append(*list, ps);

	return retval;
}

//Write error
void py_error_write(uint8_t error_code, uint8_t source) {

	pPmObj_t pframe;
	pPmObj_t pstr;
		
	PM_error.source = source;
	PM_error.error_code = error_code;

	/* Get the top frame */
	pframe = (pPmObj_t)gVmGlobal.pthread->pframe;
	tuple_getItem((pPmObj_t)((pPmFrame_t)pframe)->fo_func->f_co->co_names, -1, &pstr);	
	memcpy(PM_error.thread_name,((pPmString_t)pstr)->val,sizeof(PM_error.thread_name));
}

PmReturn_t
nat_00_dev_sys_delay_ms(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t ms_val;
	ms_val = NATIVE_GET_LOCAL(0);
	vTaskDelay(((pPmInt_t)ms_val)->val);
	NATIVE_SET_TOS(PM_NONE);
	return retval;
     
}

PmReturn_t
nat_01_dev_sys_kill_Thread(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_EX;
	return retval;
	
}

PmReturn_t
nat_02_dev_sys_func_name(pPmFrame_t *ppframe)
{

	char buf[30];
	pPmObj_t ps;
	pPmObj_t pframe;
	pPmObj_t pstr;
	
	PmReturn_t retval = PM_RET_OK;
	
	/* Get the top frame */
	pframe = (pPmObj_t)gVmGlobal.pthread->pframe;
	
	retval = tuple_getItem((pPmObj_t)((pPmFrame_t)pframe)->fo_func->f_co->co_names, -1, &pstr);	
	sprintf(buf,"%s",((pPmString_t)pstr)->val);	
	if (retval == PM_RET_OK) {
		retval = string_new(buf, &ps);
    		NATIVE_SET_TOS(ps);
    	}
    	
	return retval;
	
}

PmReturn_t
nat_03_dev_sys_get_error(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t pl;
	uint8_t const *str = (uint8_t const *)PM_error.thread_name;

	uint8_t const *pstr = str;
	
	retval = list_new(&pl);
	py_add_int_toList(PM_error.source, &pl);
	py_add_int_toList(PM_error.error_code, &pl);
	py_add_str_toList((char*)pstr, &pl);

	NATIVE_SET_TOS(pl);
	return retval;
	
}

PmReturn_t
nat_04_dev_sys_addCallback(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	pPmObj_t pf;
	pPmObj_t ps;
	char buf[20];

	/* If wrong number of args, raise TypeError */
	if (NATIVE_GET_NUM_ARGS() != 1)
	{
	   PM_RAISE(retval, PM_RET_EX_TYPE);
	   return retval;
	}

	//Check type
	pf = NATIVE_GET_LOCAL(0);
	if (OBJ_GET_TYPE(pf) != OBJ_TYPE_FXN)
	{
	   PM_RAISE(retval, PM_RET_EX_TYPE);
	   return retval;
	}

	//Get function name
	retval = tuple_getItem((pPmObj_t)((pPmFunc_t)pf)->f_co->co_names, -1, &ps);	
	sprintf(buf,"%s",((pPmString_t)ps)->val);	

	//Search function by name
	for (int i=0; i<PY_COUNT_CALLBACKS; i++) {
		if (strstr(PY_callback[i].callback_name, buf) !=0){
			PY_callback[i].PY_func = pf; //Record function
			PY_callback[i].callback_status = PY_CALLBACK_STOP; //Record status
			NATIVE_SET_TOS(PM_NONE);
			retval = PM_RET_OK;
			return retval;
		}
	}
	
	NATIVE_SET_TOS(PM_NONE);
	retval = PM_RET_NO;
	return retval;
	
}

PmReturn_t
nat_05_dev_sys_ClearCallback(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	char name[20];
	
	//Get function name
     py_get_functionName(name); 	

	//Search function by name
	for (int i=0; i<PY_COUNT_CALLBACKS; i++) {
		if (strstr(PY_callback[i].callback_name, name) !=0){
			PY_callback[i].callback_status = PY_CALLBACK_STOP; //Record status
			NATIVE_SET_TOS(PM_NONE);
			retval = PM_RET_OK;
			return retval;
		}
	}
	
	NATIVE_SET_TOS(PM_NONE);
	retval = PM_RET_NO;
	return retval;
	
}

PmReturn_t
nat_06_dev_sys_getCallbackValue(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	char name[20];
	pPmObj_t pl;
	
	//Get function name
     py_get_functionName(name); 	

     //Search function by name
	for (int i=0; i<PY_COUNT_CALLBACKS; i++) {
		if (strstr(PY_callback[i].callback_name, name) !=0){
			retval = list_new(&pl);

			//Make params
			switch(i) {
			case PY_MQTT_CALLBACK:
				break;
			case PY_GPIO_CALLBACK:	
				break;
			case PY_MODEM_CALLBACK:
				break;
			}
			
			NATIVE_SET_TOS(pl);
			retval = PM_RET_OK;
			return retval;
		}
	}
	
	NATIVE_SET_TOS(PM_NONE);
	retval = PM_RET_NO;
	return retval;
	
}

PmReturn_t
nat_07_digio_relayOut_nat(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	HAL_StatusTypeDef retstat;
	
	//Getting values
	uint8_t relNum = py_get_uint8_t(0);
	uint8_t state = py_get_uint8_t(1);

	//Relay out
	retstat = DC_relayOut(relNum, state);
	
	if (retstat != HAL_OK)
	{
		py_error_write((uint8_t)retstat, relNum);
		retval = PM_RET_ERR;
	}
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_08_digio_ledOut(pPmFrame_t *ppframe)
{

	PmReturn_t retval = PM_RET_OK;
	HAL_StatusTypeDef retstat;
	
	//Getting values
	uint8_t led = py_get_uint8_t(0);
	uint8_t state = py_get_uint8_t(1);

	//Relay out
	DC_LedOut((LED_t)led, state);
	
	NATIVE_SET_TOS(PM_NONE);
	return retval;
	
}

PmReturn_t
nat_09_list_append(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    PmReturn_t retval = PM_RET_OK;

    /* Raise TypeError if it's not a list or wrong number of args, */
    pl = NATIVE_GET_LOCAL(0);
    if ((OBJ_GET_TYPE(pl) != OBJ_TYPE_LST) || (NATIVE_GET_NUM_ARGS() != 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Append the object to the list */
    retval = list_append(pl, NATIVE_GET_LOCAL(1));

    NATIVE_SET_TOS(PM_NONE);

    return retval;
    
}

PmReturn_t
nat_10_list_index(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    pPmObj_t po;
    pPmObj_t pi;
    PmReturn_t retval = PM_RET_OK;
    uint16_t i;

    /* Raise TypeError if it's not a list or wrong number of args, */
    pl = NATIVE_GET_LOCAL(0);
    if ((OBJ_GET_TYPE(pl) != OBJ_TYPE_LST) || (NATIVE_GET_NUM_ARGS() != 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Get the index of the object in the list */
    po = NATIVE_GET_LOCAL(1);
    retval = list_index(pl, po, &i);

    if (retval == PM_RET_EX_VAL)
    {
        PM_RAISE(retval, PM_RET_EX_VAL);
        return retval;
    }

    int_new((int32_t)i, &pi);
    NATIVE_SET_TOS(pi);

    return retval;
    
}

PmReturn_t
nat_11_list_insert(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    pPmObj_t pi;
    pPmObj_t po;
    PmReturn_t retval = PM_RET_OK;
    uint16_t i;

    /*
     * Raise TypeError if wrong number of args, first arg is not a list, or
     * second arg is not an int
     */
    pl = NATIVE_GET_LOCAL(0);
    pi = NATIVE_GET_LOCAL(1);
    po = NATIVE_GET_LOCAL(2);
    if ((NATIVE_GET_NUM_ARGS() != 3)
        || (OBJ_GET_TYPE(pl) != OBJ_TYPE_LST)
        || (OBJ_GET_TYPE(pi) != OBJ_TYPE_INT) )
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Insert the object before the given index */
    i = (uint16_t)((pPmInt_t)pi)->val;
    retval = list_insert(pl, i, po);

    if (retval != PM_RET_OK)
    {
        PM_RAISE(retval, PM_RET_EX_SYS);
    }

    NATIVE_SET_TOS(PM_NONE);

    return retval;
    
}

PmReturn_t
nat_12_list_pop(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    pPmObj_t pi;
    pPmObj_t po;
    PmReturn_t retval = PM_RET_OK;
    int16_t i;

    /*
     * Raise TypeError if first arg is not a list o second arg is not an int
     * or there are the wrong number of arguments
     */
    pl = NATIVE_GET_LOCAL(0);
    if (OBJ_GET_TYPE(pl) != OBJ_TYPE_LST)
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    pi = NATIVE_GET_LOCAL(1);
    if (NATIVE_GET_NUM_ARGS() == 2)
    {
        if (OBJ_GET_TYPE(pi) != OBJ_TYPE_INT)
        {
            PM_RAISE(retval, PM_RET_EX_TYPE);
            return retval;
        }
        i = (uint16_t)((pPmInt_t)pi)->val;
    }
    else
    {
        i = -1;
    }
    if ((NATIVE_GET_NUM_ARGS() < 1) || (NATIVE_GET_NUM_ARGS() > 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Get the object at the given index */
    retval = list_getItem(pl, i, &po);
    PM_RETURN_IF_ERROR(retval);

    /* Return the object to the caller */
    NATIVE_SET_TOS(po);

    /* Remove the object from the given index */
    retval = list_delItem(pl, i);
    PM_RETURN_IF_ERROR(retval);

    return retval;
    
}

PmReturn_t
nat_13_list_remove(pPmFrame_t *ppframe)
{

    pPmObj_t pl;
    pPmObj_t pv;
    PmReturn_t retval = PM_RET_OK;

    /* Raise TypeError if it's not a list or wrong number of args, */
    pl = NATIVE_GET_LOCAL(0);
    if ((OBJ_GET_TYPE(pl) != OBJ_TYPE_LST) || (NATIVE_GET_NUM_ARGS() != 2))
    {
        PM_RAISE(retval, PM_RET_EX_TYPE);
        return retval;
    }

    /* Remove the value from the list */
    pv = NATIVE_GET_LOCAL(1);
    retval = list_remove(pl, pv);
    if (retval != PM_RET_OK)
    {
        PM_RAISE(retval, retval);
    }

    NATIVE_SET_TOS(PM_NONE);

    return retval;
    
}

/* Native function lookup table */
pPmNativeFxn_t const std_nat_fxn_table[] =
{
    nat_00_dev_sys_delay_ms,
    nat_01_dev_sys_kill_Thread,
    nat_02_dev_sys_func_name,
    nat_03_dev_sys_get_error,
    nat_04_dev_sys_addCallback,
    nat_05_dev_sys_ClearCallback,
    nat_06_dev_sys_getCallbackValue,
    nat_07_digio_relayOut_nat,
    nat_08_digio_ledOut,
    nat_09_list_append,
    nat_10_list_index,
    nat_11_list_insert,
    nat_12_list_pop,
    nat_13_list_remove,
};
